// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//----------------------Flutter App Firebase Step 3-----------------
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
//--------------------------------------------------

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEiYzFuXgJnVoZ10LUOIokfWdWrzO9YA',
    appId: '1:461147263039:web:4ed9d401f36252e9a2688a',
    messagingSenderId: '461147263039',
    projectId: 'insta-print-app',
    authDomain: 'insta-print-app.firebaseapp.com',
    storageBucket: 'insta-print-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMHGA8EBHJaeGuVAAkt0o3ogDhwIZhNOE',
    appId: '1:461147263039:android:081edcfa16812229a2688a',
    messagingSenderId: '461147263039',
    projectId: 'insta-print-app',
    storageBucket: 'insta-print-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYz-dezyLi9ST_B-lIJJb0Yy_ajlq2Gg',
    appId: '1:461147263039:ios:7dbe40bf0776e658a2688a',
    messagingSenderId: '461147263039',
    projectId: 'insta-print-app',
    storageBucket: 'insta-print-app.appspot.com',
    iosBundleId: 'com.example.instaPrintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuYz-dezyLi9ST_B-lIJJb0Yy_ajlq2Gg',
    appId: '1:461147263039:ios:7dbe40bf0776e658a2688a',
    messagingSenderId: '461147263039',
    projectId: 'insta-print-app',
    storageBucket: 'insta-print-app.appspot.com',
    iosBundleId: 'com.example.instaPrintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEiYzFuXgJnVoZ10LUOIokfWdWrzO9YA',
    appId: '1:461147263039:web:70239c63f4741a24a2688a',
    messagingSenderId: '461147263039',
    projectId: 'insta-print-app',
    authDomain: 'insta-print-app.firebaseapp.com',
    storageBucket: 'insta-print-app.appspot.com',
  );

}